using System;
using System.Collections.Generic;
using GameSparks.Core;
using GameSparks.Api.Responses;

namespace GameSparks.Api.Requests
{
    /// <summary>
    /// Base class for autogenerated requests. You should never have to use this class directly. 
    /// </summary>
    public class CustomRequest : GSTypedRequest<CustomRequest, CustomResponse>
    {

        public CustomRequest(String requestType) : base(requestType) { }

        public CustomRequest(IDictionary<string, object> data) : base(data) { }

        protected override GSTypedResponse BuildResponse(GSObject response)
        {
            return new CustomResponse(response);
        }

        public CustomRequest AddString(String key, String value)
        {
            request.AddString(key, value);
            return this;
        }

        public CustomRequest AddNumber(String key, long value)
        {
            request.AddNumber(key, value);
            return this;
        }

        public CustomRequest AddObject(String key, GSRequestData value)
        {
            request.AddObject(key, value);
            return this;
        }

    }
}

