// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using GameSparks.RT;
using System.Collections.Generic;

namespace GameSparks.RT.Proto
{
    internal partial class Packet
    {
        public int OpCode { get; set; }

        public int? SequenceNumber { get; set; }

        public int? RequestId { get; set; }

        public List<int> TargetPlayers { get; set; }

        public int? Sender { get; set; }

        public bool? Reliable { get; set; }

        public RTData Data { get; set; }

        public byte[] Payload { get; set; }

    }

}
